"""Fix foreign key issue

Revision ID: b748d9091c77
Revises: cc346ddcdbe0
Create Date: 2025-07-09 14:43:56.214904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b748d9091c77'
down_revision: Union[str, Sequence[str], None] = 'cc346ddcdbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qnatable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('qna_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['workspace.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qnatable')
    # ### end Alembic commands ###
