"""Initial schema

Revision ID: cc346ddcdbe0
Revises: 74ebd86e9d63
Create Date: 2025-07-09 14:15:52.423269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc346ddcdbe0'
down_revision: Union[str, Sequence[str], None] = '74ebd86e9d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('workspace', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_column('workspace', 'id')
    op.drop_column('workspace', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('workspace', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('workspace', 'workspace_id')
    op.drop_column('nodes', 'is_completed')
    # ### end Alembic commands ###
